SELECT CONCAT('ALTER TABLE `', c.TABLE_NAME, '` ADD PRIMARY KEY (`', c.COLUMN_NAME, '`);') AS stmt
FROM INFORMATION_SCHEMA.COLUMNS c
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
  ON tc.TABLE_SCHEMA = c.TABLE_SCHEMA
 AND tc.TABLE_NAME = c.TABLE_NAME
 AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
WHERE c.TABLE_SCHEMA = 'dbo13ju3uv0emv'
  AND c.COLUMN_NAME = 'id'
  AND c.COLUMN_KEY = ''
  AND c.IS_NULLABLE = 'NO'
  AND tc.CONSTRAINT_NAME IS NULL
  AND c.TABLE_NAME NOT IN ('admin_dashboard_summary','device_summary','report_summary','v_device_summary','v_security_events','v_user_stats')
ORDER BY c.TABLE_NAME;
