SELECT 'api_keys' AS tbl, COUNT(*) - COUNT(DISTINCT id) AS dupes FROM api_keys
UNION ALL SELECT 'audit_logs', COUNT(*) - COUNT(DISTINCT id) FROM audit_logs
UNION ALL SELECT 'data_exports', COUNT(*) - COUNT(DISTINCT id) FROM data_exports
UNION ALL SELECT 'device_categories', COUNT(*) - COUNT(DISTINCT id) FROM device_categories
UNION ALL SELECT 'device_check_logs', COUNT(*) - COUNT(DISTINCT id) FROM device_check_logs
UNION ALL SELECT 'device_checks', COUNT(*) - COUNT(DISTINCT id) FROM device_checks
UNION ALL SELECT 'device_transfers', COUNT(*) - COUNT(DISTINCT id) FROM device_transfers
UNION ALL SELECT 'device_verification_history', COUNT(*) - COUNT(DISTINCT id) FROM device_verification_history
UNION ALL SELECT 'device_verifications', COUNT(*) - COUNT(DISTINCT id) FROM device_verifications
UNION ALL SELECT 'devices', COUNT(*) - COUNT(DISTINCT id) FROM devices
UNION ALL SELECT 'imei_checks', COUNT(*) - COUNT(DISTINCT id) FROM imei_checks
UNION ALL SELECT 'kyc_batches', COUNT(*) - COUNT(DISTINCT id) FROM kyc_batches
UNION ALL SELECT 'kyc_verifications', COUNT(*) - COUNT(DISTINCT id) FROM kyc_verifications
UNION ALL SELECT 'landing_content', COUNT(*) - COUNT(DISTINCT id) FROM landing_content
UNION ALL SELECT 'law_enforcement_agencies', COUNT(*) - COUNT(DISTINCT id) FROM law_enforcement_agencies
UNION ALL SELECT 'marketplace_listings', COUNT(*) - COUNT(DISTINCT id) FROM marketplace_listings
UNION ALL SELECT 'marketplace_messages', COUNT(*) - COUNT(DISTINCT id) FROM marketplace_messages
UNION ALL SELECT 'migrations', COUNT(*) - COUNT(DISTINCT id) FROM migrations
UNION ALL SELECT 'notification_queue', COUNT(*) - COUNT(DISTINCT id) FROM notification_queue
UNION ALL SELECT 'notification_settings', COUNT(*) - COUNT(DISTINCT id) FROM notification_settings
UNION ALL SELECT 'notifications', COUNT(*) - COUNT(DISTINCT id) FROM notifications
UNION ALL SELECT 'otps', COUNT(*) - COUNT(DISTINCT id) FROM otps
UNION ALL SELECT 'ownership_transfers', COUNT(*) - COUNT(DISTINCT id) FROM ownership_transfers
UNION ALL SELECT 'payment_methods', COUNT(*) - COUNT(DISTINCT id) FROM payment_methods
UNION ALL SELECT 'push_subscriptions', COUNT(*) - COUNT(DISTINCT id) FROM push_subscriptions
UNION ALL SELECT 'recovery_agents', COUNT(*) - COUNT(DISTINCT id) FROM recovery_agents
UNION ALL SELECT 'recovery_services', COUNT(*) - COUNT(DISTINCT id) FROM recovery_services
UNION ALL SELECT 'reports', COUNT(*) - COUNT(DISTINCT id) FROM reports
UNION ALL SELECT 'suspicious_activity_alerts', COUNT(*) - COUNT(DISTINCT id) FROM suspicious_activity_alerts
UNION ALL SELECT 'system_alerts', COUNT(*) - COUNT(DISTINCT id) FROM system_alerts
UNION ALL SELECT 'system_notifications', COUNT(*) - COUNT(DISTINCT id) FROM system_notifications
UNION ALL SELECT 'system_settings', COUNT(*) - COUNT(DISTINCT id) FROM system_settings
UNION ALL SELECT 'transactions', COUNT(*) - COUNT(DISTINCT id) FROM transactions
UNION ALL SELECT 'user_preferences', COUNT(*) - COUNT(DISTINCT id) FROM user_preferences
UNION ALL SELECT 'user_sessions', COUNT(*) - COUNT(DISTINCT id) FROM user_sessions
UNION ALL SELECT 'user_suspensions', COUNT(*) - COUNT(DISTINCT id) FROM user_suspensions
HAVING (COUNT(*) - COUNT(DISTINCT id)) > 0;
